#ifndef GLOBALES_H
#define GLOBALES_H

#define TABLA_TRANSICION_COLUMNAS 4

#define CANTIDAD_ESTADOS 6

#define ESTADO_INICIAL 0

#define ESTADO_RECHAZO 5

#define CANTIDAD_ESTADOS_FINALES 2

#define MAX_LONGITUD_PALABRA 255

#define MAX_CANTIDAD_PALABRAS 30

#define ALFABETO "0123456789.B"

#define EXPRESION_REGULAR "[01].[0-9]? | [01]+B"

#endif
